# ------------------------------------------------------------------------
# Copyright (c) 2022 megvii-model. All Rights Reserved.
# ------------------------------------------------------------------------
# Modified from BasicSR (https://github.com/xinntao/BasicSR)
# Copyright 2018-2020 BasicSR Authors
# ------------------------------------------------------------------------
# general settings
name: Baseline-DPDD-width32
model_type: ImageRestorationModel
scale: 1
num_gpu: 4
manual_seed: 42

datasets:
  train:
    name: dpdd16-train
    type: TripletImageDataset
    dataroot_lqL: ./datasets/DPDD/train/inputL_crops.lmdb
    dataroot_lqR: ./datasets/DPDD/train/inputR_crops.lmdb
    dataroot_gt: ./datasets/DPDD/train/target_crops.lmdb

    filename_tmpl: '{}'
    io_backend:
      type: lmdb

    gt_size: 256
    use_flip: true
    use_rot: true

    # data loader
    use_shuffle: true
    num_worker_per_gpu: 4
    batch_size_per_gpu: 4
    dataset_enlarge_ratio: 1
    prefetch_mode: ~

  val:
    name: dpdd16-val
    type: TripletImageDataset
    dataroot_lqL: ./datasets/DPDD/test/inputL.lmdb
    dataroot_lqR: ./datasets/DPDD/test/inputR.lmdb
    dataroot_gt: ./datasets/DPDD/test/target.lmdb
    io_backend:
      type: lmdb


network_g:
  type: BaselineLocal
  inp_channels: 6
  out_channels: 3
  dim: 16
  dual_pixel_task: True

# path
path:
  pretrain_network_g: ~
  strict_load_g: true
  resume_state: ~

# training settings
train:
  optim_g:
    type: AdamW
    lr: !!float 3e-4
    weight_decay: !!float 1e-2
    betas: [0.9, 0.999]

  scheduler:
    type: TrueCosineAnnealingLR
    T_max: 100000
    eta_min: !!float 1e-6

  total_iter: 100000
  warmup_iter: -1 # no warm up

  # losses
  pixel_opt:
    type: PSNRLoss
    loss_weight: 1
    reduction: mean

# validation settings
val:
  val_freq: !!float 1e4
  save_img: false


  metrics:
    psnr: # metric name, can be arbitrary
      type: calculate_psnr
      crop_border: 0
      test_y_channel: false
    ssim:
      type: calculate_ssim
      crop_border: 0
      test_y_channel: false

# logging settings
logger:
  print_freq: 200
  save_checkpoint_freq: !!float 5e3
  use_tb_logger: true
  wandb:
    project: ~
    resume_id: ~

# dist training settings
dist_params:
  backend: nccl
  port: 29500
